{
    "type": [
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        2,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        2,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        3,
        3,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        3,
        3,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        3,
        3,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        3,
        3,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        3,
        3,
        3,
        3,
        2,
        3,
        3,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        2
    ],
    "data": [
        "",
        ">>> ",
        "y = df['body_mass_g']",
        ">>> ",
        "",
        ">>> ",
        "model = LinearRegression().fit(X, y)",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "print(f\"R^2 {model.score(X,y)}\")",
        "Error: unexpected string constant in \"print(f\"R^2 {model.score(X,y)}\"\"\n",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "print(f\"R^2 {model.score(X,y)}\")",
        "R^2 0.8555368759537614\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Intercept {model.intercept_}\")",
        "Intercept 2169.269720939398\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Columns {X.columns}\")",
        "Columns Index(['bill_length_mm', 'species_Chinstrap', 'species_Gentoo', 'sex_male'], dtype='object')\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Coefficients {model.coef_}\")",
        "Coefficients [  32.53688677 -298.76553447 1094.86739145  547.36692408]\r\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = vetiver_pin_write(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'vetiver_pin_write' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "X = get_dummies(df[['bill_length_mm', 'species', 'sex']], drop_first = True)",
        ">>> ",
        "",
        ">>> ",
        "y = df['body_mass_g']",
        ">>> ",
        "",
        ">>> ",
        "model = LinearRegression().fit(X, y)",
        ">>> ",
        "",
        ">>> ",
        "print(f\"R^2 {model.score(X,y)}\")",
        "R^2 0.8555368759537614\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Intercept {model.intercept_}\")",
        "Intercept 2169.269720939398\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Columns {X.columns}\")",
        "Columns Index(['bill_length_mm', 'species_Chinstrap', 'species_Gentoo', 'sex_male'], dtype='object')\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Coefficients {model.coef_}\")",
        "Coefficients [  32.53688677 -298.76553447 1094.86739145  547.36692408]\r\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = vetiver_pin_write(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'vetiver_pin_write' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        ">>> ",
        "",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "v = VetiverModel.from_pin(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "library(vetiver)",
        "Warning message:\n",
        "package ‘vetiver’ was built under R version 4.2.3 \n",
        "> ",
        "detach(\"package:vetiver\", unload = TRUE)",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "v = vetiver_pin_write(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'vetiver_pin_write' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "v = vetiver_pin_write(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'vetiver_pin_write' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "v = vetiver_pin_write(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "v = VetiverModel.from_pin(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "v = VetiverModel.from_pin(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "v = VetiverModel.from_pin(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "v = VetiverModel.from_pin(b, 'penguin_model')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "p = vetiver_pin_write(board, v, ..., check_renv = FALSE)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'board' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"R^2 {model.score(X,y)}\")",
        "R^2 0.8555368759537614\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Intercept {model.intercept_}\")",
        "Intercept 2169.269720939398\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Columns {X.columns}\")",
        "Columns Index(['bill_length_mm', 'species_Chinstrap', 'species_Gentoo', 'sex_male'], dtype='object')\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Coefficients {model.coef_}\")",
        "Coefficients [  32.53688677 -298.76553447 1094.86739145  547.36692408]\r\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = vetiver_pin_write(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nTypeError: vetiver_pin_write() got an unexpected keyword argument 'model_name'\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "b = board('data/model', allow_pickle_read=True)",
        "Error in board(\"data/model\", allow_pickle_read = True) : \n  could not find function \"board\"\n",
        "> ",
        "p = vetiver_pin_write('penuin_model', v, ..., check_renv = FALSE)",
        "Error in vetiver_pin_write(\"penuin_model\", v, ..., check_renv = FALSE) : \n  could not find function \"vetiver_pin_write\"\n",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v, ..., check_renv = FALSE)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'FALSE' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 45;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\vetiver\\pin_read_write.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\vetiver\\pin_read_write.py\u001B]8;;\u0007\u001B[39m\", line 45, in vetiver_pin_write\n    if not board.allow_pickle_read:\nAttributeError: 'str' object has no attribute 'allow_pickle_read'\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v, c)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'c' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 45;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\vetiver\\pin_read_write.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\vetiver\\pin_read_write.py\u001B]8;;\u0007\u001B[39m\", line 45, in vetiver_pin_write\n    if not board.allow_pickle_read:\nAttributeError: 'str' object has no attribute 'allow_pickle_read'\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 45;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\vetiver\\pin_read_write.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\vetiver\\pin_read_write.py\u001B]8;;\u0007\u001B[39m\", line 45, in vetiver_pin_write\n    if not board.allow_pickle_read:\nAttributeError: 'str' object has no attribute 'allow_pickle_read'\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "from vetiver import pins.board_folder",
        "  File \"<string>\", line 1\n    from vetiver import pins.board_folder\n                            ^\nSyntaxError: invalid syntax\n",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 45;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\vetiver\\pin_read_write.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\vetiver\\pin_read_write.py\u001B]8;;\u0007\u001B[39m\", line 45, in vetiver_pin_write\n    if not board.allow_pickle_read:\nAttributeError: 'str' object has no attribute 'allow_pickle_read'\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 45;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\vetiver\\pin_read_write.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\vetiver\\pin_read_write.py\u001B]8;;\u0007\u001B[39m\", line 45, in vetiver_pin_write\n    if not board.allow_pickle_read:\nAttributeError: 'str' object has no attribute 'allow_pickle_read'\n",
        ">>> ",
        "",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "p = vetiver_pin_write('penuin_model', v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 45;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\vetiver\\pin_read_write.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\vetiver\\pin_read_write.py\u001B]8;;\u0007\u001B[39m\", line 45, in vetiver_pin_write\n    if not board.allow_pickle_read:\nAttributeError: 'str' object has no attribute 'allow_pickle_read'\n",
        ">>> ",
        "",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        "\nRestarting R session...\n\n",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'model' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'model' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'model' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "library(palmerpenguins)",
        "> ",
        "library(dplyr)",
        "> ",
        "library(ggplot2)",
        "> ",
        "",
        "> ",
        "df <- palmerpenguins::penguins",
        "> ",
        "df %>%",
        "+ ",
        "  group_by(species, sex) %>%",
        "+ ",
        "  summarise(",
        "+ ",
        "    across(",
        "+ ",
        "      where(is.numeric), ",
        "+ ",
        "      \\(x) mean(x, na.rm = TRUE)",
        "+ ",
        "      )",
        "+ ",
        "    ) %>%",
        "+ ",
        "  knitr::kable()",
        "> ",
        "",
        "> ",
        "df %>%",
        "+ ",
        "  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +",
        "+ ",
        "  geom_point() + ",
        "+ ",
        "  geom_smooth(method = \"lm\")",
        "> ",
        "renv::snapshot()",
        "WARNING: One or more problems were discovered while enumerating dependencies.\n\n# C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/Chapter1.qmd --------\nError: Duplicate map key: 'format'\n\nPlease see `?renv::dependencies` for more information.\n\n",
        "Do you want to proceed? [Y/n]: ",
        "reticulate::repl_python()",
        "- Unrecognized response: please enter 'y' or 'n', or type Ctrl + C to cancel.\n",
        "Do you want to proceed? [Y/n]: ",
        "reticulate::repl_python()",
        "- Unrecognized response: please enter 'y' or 'n', or type Ctrl + C to cancel.\n\nRestarting R session...\n\n",
        "> ",
        "df %>%",
        "+ ",
        "  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +",
        "+ ",
        "  geom_point() + ",
        "+ ",
        "  geom_smooth(method = \"lm\")",
        "Error in df %>% ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) : \n  could not find function \"%>%\"\n",
        "> ",
        "library(palmerpenguins)",
        "> ",
        "library(dplyr)",
        "> ",
        "library(ggplot2)",
        "> ",
        "",
        "> ",
        "df <- palmerpenguins::penguins",
        "> ",
        "df %>%",
        "+ ",
        "  group_by(species, sex) %>%",
        "+ ",
        "  summarise(",
        "+ ",
        "    across(",
        "+ ",
        "      where(is.numeric), ",
        "+ ",
        "      \\(x) mean(x, na.rm = TRUE)",
        "+ ",
        "      )",
        "+ ",
        "    ) %>%",
        "+ ",
        "  knitr::kable()",
        "> ",
        "",
        "> ",
        "df %>%",
        "+ ",
        "  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +",
        "+ ",
        "  geom_point() + ",
        "+ ",
        "  geom_smooth(method = \"lm\")",
        "> ",
        "renv::snapshot()",
        "WARNING: One or more problems were discovered while enumerating dependencies.\n\n# C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/Chapter1.qmd --------\nError: Duplicate map key: 'format'\n\nPlease see `?renv::dependencies` for more information.\n\n\nRestarting R session...\n\n",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "from palmerpenguins import penguins",
        ">>> ",
        "",
        ">>> ",
        "from pandas import get_dummies",
        ">>> ",
        "",
        ">>> ",
        "import numpy as np",
        ">>> ",
        "",
        ">>> ",
        "from sklearn.linear_model import LinearRegression",
        ">>> ",
        "",
        ">>> ",
        "from sklearn import preprocessing",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'model' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'model' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'model' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "X = get_dummies(df[['bill_length_mm', 'species', 'sex']], drop_first = True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'df' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "y = df['body_mass_g']",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'df' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "model = LinearRegression().fit(X, y)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'X' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "library(palmerpenguins)",
        "> ",
        "library(dplyr)",
        "> ",
        "library(ggplot2)",
        "> ",
        "",
        "> ",
        "df <- palmerpenguins::penguins",
        "> ",
        "df %>%",
        "+ ",
        "  group_by(species, sex) %>%",
        "+ ",
        "  summarise(",
        "+ ",
        "    across(",
        "+ ",
        "      where(is.numeric), ",
        "+ ",
        "      \\(x) mean(x, na.rm = TRUE)",
        "+ ",
        "      )",
        "+ ",
        "    ) %>%",
        "+ ",
        "  knitr::kable()",
        "> ",
        "",
        "> ",
        "df %>%",
        "+ ",
        "  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +",
        "+ ",
        "  geom_point() + ",
        "+ ",
        "  geom_smooth(method = \"lm\")",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "from palmerpenguins import penguins",
        ">>> ",
        "",
        ">>> ",
        "from pandas import get_dummies",
        ">>> ",
        "",
        ">>> ",
        "import numpy as np",
        ">>> ",
        "",
        ">>> ",
        "from sklearn.linear_model import LinearRegression",
        ">>> ",
        "",
        ">>> ",
        "from sklearn import preprocessing",
        ">>> ",
        "",
        ">>> ",
        "df = penguins.load_penguins().dropna()",
        ">>> ",
        "",
        ">>> ",
        "df.head(3)",
        "  species     island  bill_length_mm  ...  body_mass_g     sex  year\r\n0  Adelie  Torgersen            39.1  ...       3750.0    male  2007\r\n1  Adelie  Torgersen            39.5  ...       3800.0  female  2007\r\n2  Adelie  Torgersen            40.3  ...       3250.0  female  2007\r\n\r\n[3 rows x 8 columns]\r\n",
        ">>> ",
        "",
        ">>> ",
        "X = get_dummies(df[['bill_length_mm', 'species', 'sex']], drop_first = True)",
        ">>> ",
        "",
        ">>> ",
        "y = df['body_mass_g']",
        ">>> ",
        "",
        ">>> ",
        "model = LinearRegression().fit(X, y)",
        ">>> ",
        "",
        ">>> ",
        "print(f\"R^2 {model.score(X,y)}\")",
        "R^2 0.8555368759537614\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Intercept {model.intercept_}\")",
        "Intercept 2169.269720939398\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Columns {X.columns}\")",
        "Columns Index(['bill_length_mm', 'species_Chinstrap', 'species_Gentoo', 'sex_male'], dtype='object')\r\n",
        ">>> ",
        "",
        ">>> ",
        "print(f\"Coefficients {model.coef_}\")",
        "Coefficients [  32.53688677 -298.76553447 1094.86739145  547.36692408]\r\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverModel",
        ">>> ",
        "v = VetiverModel(model, model_name='penguin_model', prototype_data=X)",
        ">>> ",
        "",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'pins' is not defined\n",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'b' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "import pins",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Model Cards provide a framework for transparent, responsible reporting. \r\n Use the vetiver `.qmd` Quarto template as a place to start, \r\n with vetiver.model_card()",
        "\r\n",
        "Writing pin:\r\nName: 'penguin_model'\r\nVersion: 20240307T191023Z-a6f9b",
        "\r\n",
        ">>> ",
        "",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Model Cards provide a framework for transparent, responsible reporting. \r\n Use the vetiver `.qmd` Quarto template as a place to start, \r\n with vetiver.model_card()",
        "\r\n",
        "Writing pin:\r\nName: 'penguin_model'\r\nVersion: 20240307T191038Z-a6f9b",
        "\r\n",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "library(pins)",
        "Warning message:\n",
        "package ‘pins’ was built under R version 4.2.3 \n",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Model Cards provide a framework for transparent, responsible reporting. \r\n Use the vetiver `.qmd` Quarto template as a place to start, \r\n with vetiver.model_card()",
        "\r\n",
        "Writing pin:\r\nName: 'penguin_model'\r\nVersion: 20240307T191047Z-a6f9b",
        "\r\n",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "detach(\"package:pins\", unload = TRUE)",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "from pins import board_folder",
        ">>> ",
        "from vetiver import vetiver_pin_write",
        ">>> ",
        "b = pins.board_folder('data/model', allow_pickle_read=True)",
        ">>> ",
        "p = vetiver_pin_write(b, v, versioned=True )",
        "Model Cards provide a framework for transparent, responsible reporting. \r\n Use the vetiver `.qmd` Quarto template as a place to start, \r\n with vetiver.model_card()",
        "\r\n",
        "Writing pin:\r\nName: 'penguin_model'\r\nVersion: 20240307T191634Z-a6f9b",
        "\r\n",
        ">>> ",
        "",
        ">>> ",
        "quit",
        "> ",
        "app = VetiverAPI(v, check_prototype=True)",
        "Error in VetiverAPI(v, check_prototype = True) : \n  could not find function \"VetiverAPI\"\n",
        "> ",
        "reticulate::repl_python()",
        "Python 3.9.5 (C:/Users/C25Joshua.Pym/OneDrive - afacademy.af.edu/Documents/Final Project for Joshua Pym/.venv/Scripts/python.exe)\nReticulate 1.35.0 REPL -- A Python interpreter in R.\nEnter 'exit' or 'quit' to exit the REPL and return to R.\n",
        ">>> ",
        "from vetiver import VetiverAPI",
        ">>> ",
        "app = VetiverAPI(v, check_prototype=True)",
        ">>> ",
        "",
        ">>> ",
        "app.run(port = 8080)",
        "INFO:     Started server process [24828]\r\n",
        "INFO:     Waiting for application startup.\r\n",
        "INFO:     VetiverAPI starting...\r\n",
        "INFO:     Application startup complete.\r\n",
        "INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)\r\n",
        "INFO:     127.0.0.1:64834 - \"GET / HTTP/1.1\" 307 Temporary Redirect\r\nINFO:     127.0.0.1:64834 - \"GET /__docs__ HTTP/1.1\" 200 OK\r\nINFO:     127.0.0.1:64834 - \"GET /openapi.json HTTP/1.1\" 200 OK\r\nINFO:     127.0.0.1:64834 - \"GET /favicon.ico HTTP/1.1\" 404 Not Found\r\n",
        "INFO:     Shutting down\r\n",
        "INFO:     Waiting for application shutdown.\r\n",
        "INFO:     Application shutdown complete.\r\nINFO:     Finished server process [24828]\r\n",
        ">>> ",
        "from vetiver import VetiverAPI",
        ">>> ",
        "app = VetiverAPI(v, check_prototype=True)",
        ">>> ",
        "",
        ">>> ",
        "import duckdb",
        ">>> ",
        "from palmerpenguins import penguins",
        ">>> ",
        "",
        ">>> ",
        "con = duckdb.connect('my-db.duckdb')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'duckdb' is not defined\n",
        ">>> ",
        "df = penguins.load_penguins()",
        ">>> ",
        "con.execute('CREATE TABLE penguins AS SELECT * FROM df')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'con' is not defined\n",
        ">>> ",
        "con.close()",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'con' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "import duckdb",
        ">>> ",
        "from palmerpenguins import penguins",
        ">>> ",
        "",
        ">>> ",
        "con = duckdb.connect('my-db.duckdb')",
        ">>> ",
        "df = penguins.load_penguins()",
        ">>> ",
        "con.execute('CREATE TABLE penguins AS SELECT * FROM df')",
        "<duckdb.duckdb.DuckDBPyConnection object at 0x000001E7EE4649B0>\r\n",
        ">>> ",
        "con.close()",
        ">>> ",
        "",
        ">>> ",
        "con = duckdb.connect('my-db.duckdb')",
        ">>> ",
        "df = con.execute(\"SELECT * FROM penguins\").fetchdf().dropna()",
        ">>> ",
        "con.close()",
        ">>> ",
        "",
        ">>> ",
        "import requests",
        ">>> ",
        "",
        ">>> ",
        "req_data = {",
        "... ",
        "  \"bill_length_mm\": 0,",
        "... ",
        "  \"species_Chinstrap\": False,",
        "... ",
        "  \"species_Gentoo\": False,",
        "... ",
        "  \"sex_male\": False",
        "... ",
        "}",
        ">>> ",
        "req = requests.post('http://127.0.0.1:8080/predict', json = [req_data])",
        "Traceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 198;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 198, in _new_conn\n    sock = connection.create_connection(\n  File \"\u001B[90m\u001B]8;line = 85;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 85, in create_connection\n    raise err\n  File \"\u001B[90m\u001B]8;line = 73;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 793;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 793, in urlopen\n    response = self._make_request(\n  File \"\u001B[90m\u001B]8;line = 496;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 496, in _make_request\n    conn.request(\n  File \"\u001B[90m\u001B]8;line = 400;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 400, in request\n    self.endheaders()\n  File \"\u001B[90m\u001B]8;line = 1248;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1248, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"\u001B[90m\u001B]8;line = 1008;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1008, in _send_output\n    self.send(msg)\n  File \"\u001B[90m\u001B]8;line = 948;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 948, in send\n    self.connect()\n  File \"\u001B[90m\u001B]8;line = 238;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 238, in connect\n    self.sock = self._new_conn()\n  File \"\u001B[90m\u001B]8;line = 213;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 213, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E7EE469BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 486;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 486, in send\n    resp = conn.urlopen(\n  File \"\u001B[90m\u001B]8;line = 847;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 847, in urlopen\n    retries = retries.increment(\n  File \"\u001B[90m\u001B]8;line = 515;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\retry.py\u001B]8;;\u0007\u001B[39m\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE469BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 115;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 59;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 589;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"\u001B[90m\u001B]8;line = 703;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 519;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE469BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n",
        ">>> ",
        "res = req.json().get('predict')[0]",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'req' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "from vetiver import VetiverAPI",
        ">>> ",
        "app = VetiverAPI(v, check_prototype=True)",
        ">>> ",
        "",
        ">>> ",
        "import duckdb",
        ">>> ",
        "from palmerpenguins import penguins",
        ">>> ",
        "",
        ">>> ",
        "con = duckdb.connect('my-db.duckdb')",
        ">>> ",
        "df = penguins.load_penguins()",
        ">>> ",
        "con.execute('CREATE TABLE penguins AS SELECT * FROM df')",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nduckdb.duckdb.CatalogException: Catalog Error: Table with name \"penguins\" already exists!\n",
        ">>> ",
        "con.close()",
        ">>> ",
        "",
        ">>> ",
        "con = duckdb.connect('my-db.duckdb')",
        ">>> ",
        "df = con.execute(\"SELECT * FROM penguins\").fetchdf().dropna()",
        ">>> ",
        "con.close()",
        ">>> ",
        "",
        ">>> ",
        "import requests",
        ">>> ",
        "",
        ">>> ",
        "req_data = {",
        "... ",
        "  \"bill_length_mm\": 0,",
        "... ",
        "  \"species_Chinstrap\": False,",
        "... ",
        "  \"species_Gentoo\": False,",
        "... ",
        "  \"sex_male\": False",
        "... ",
        "}",
        ">>> ",
        "req = requests.post('http://127.0.0.1:8080/predict', json = [req_data])",
        "Traceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 198;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 198, in _new_conn\n    sock = connection.create_connection(\n  File \"\u001B[90m\u001B]8;line = 85;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 85, in create_connection\n    raise err\n  File \"\u001B[90m\u001B]8;line = 73;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 793;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 793, in urlopen\n    response = self._make_request(\n  File \"\u001B[90m\u001B]8;line = 496;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 496, in _make_request\n    conn.request(\n  File \"\u001B[90m\u001B]8;line = 400;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 400, in request\n    self.endheaders()\n  File \"\u001B[90m\u001B]8;line = 1248;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1248, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"\u001B[90m\u001B]8;line = 1008;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1008, in _send_output\n    self.send(msg)\n  File \"\u001B[90m\u001B]8;line = 948;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 948, in send\n    self.connect()\n  File \"\u001B[90m\u001B]8;line = 238;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 238, in connect\n    self.sock = self._new_conn()\n  File \"\u001B[90m\u001B]8;line = 213;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 213, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E7EE547160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 486;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 486, in send\n    resp = conn.urlopen(\n  File \"\u001B[90m\u001B]8;line = 847;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 847, in urlopen\n    retries = retries.increment(\n  File \"\u001B[90m\u001B]8;line = 515;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\retry.py\u001B]8;;\u0007\u001B[39m\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE547160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 115;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 59;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 589;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"\u001B[90m\u001B]8;line = 703;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 519;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE547160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n",
        ">>> ",
        "res = req.json().get('predict')[0]",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'req' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "app.run(port=8080)",
        "INFO:     Started server process [24828]\r\n",
        "INFO:     Waiting for application startup.\r\n",
        "INFO:     VetiverAPI starting...\r\n",
        "INFO:     Application startup complete.\r\n",
        "INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)\r\n",
        "INFO:     Shutting down\r\n",
        "INFO:     Waiting for application shutdown.\r\n",
        "INFO:     Application shutdown complete.\r\nINFO:     Finished server process [24828]\r\n",
        ">>> ",
        "import requests",
        ">>> ",
        "",
        ">>> ",
        "req_data = {",
        "... ",
        "  \"bill_length_mm\": 0,",
        "... ",
        "  \"species_Chinstrap\": False,",
        "... ",
        "  \"species_Gentoo\": False,",
        "... ",
        "  \"sex_male\": False",
        "... ",
        "}",
        ">>> ",
        "req = requests.post('http://127.0.0.1:8080/predict', json = [req_data])",
        ">>> ",
        "res = req.json().get('predict')[0]",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'req' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "import requests",
        ">>> ",
        "",
        ">>> ",
        "req_data = {",
        "... ",
        "  \"bill_length_mm\": 0,",
        "... ",
        "  \"species_Chinstrap\": False,",
        "... ",
        "  \"species_Gentoo\": False,",
        "... ",
        "  \"sex_male\": False",
        "... ",
        "}",
        ">>> ",
        "req = requests.post('http://127.0.0.1:8080/predict', json = [req_data])",
        "Traceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 198;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 198, in _new_conn\n    sock = connection.create_connection(\n  File \"\u001B[90m\u001B]8;line = 85;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 85, in create_connection\n    raise err\n  File \"\u001B[90m\u001B]8;line = 73;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 793;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 793, in urlopen\n    response = self._make_request(\n  File \"\u001B[90m\u001B]8;line = 496;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 496, in _make_request\n    conn.request(\n  File \"\u001B[90m\u001B]8;line = 400;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 400, in request\n    self.endheaders()\n  File \"\u001B[90m\u001B]8;line = 1248;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1248, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"\u001B[90m\u001B]8;line = 1008;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1008, in _send_output\n    self.send(msg)\n  File \"\u001B[90m\u001B]8;line = 948;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 948, in send\n    self.connect()\n  File \"\u001B[90m\u001B]8;line = 238;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 238, in connect\n    self.sock = self._new_conn()\n  File \"\u001B[90m\u001B]8;line = 213;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 213, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E7EE8214F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 486;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 486, in send\n    resp = conn.urlopen(\n  File \"\u001B[90m\u001B]8;line = 847;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 847, in urlopen\n    retries = retries.increment(\n  File \"\u001B[90m\u001B]8;line = 515;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\retry.py\u001B]8;;\u0007\u001B[39m\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE8214F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 115;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 59;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 589;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"\u001B[90m\u001B]8;line = 703;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 519;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE8214F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n",
        ">>> ",
        "res = req.json().get('predict')[0]",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'req' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "app.run(port=8080)",
        "INFO:     Started server process [24828]\r\n",
        "INFO:     Waiting for application startup.\r\n",
        "INFO:     VetiverAPI starting...\r\n",
        "INFO:     Application startup complete.\r\n",
        "INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)\r\n",
        "INFO:     Shutting down\r\n",
        "INFO:     Waiting for application shutdown.\r\n",
        "INFO:     Application shutdown complete.\r\nINFO:     Finished server process [24828]\r\n",
        ">>> ",
        "import requests",
        ">>> ",
        "",
        ">>> ",
        "req_data = {",
        "... ",
        "  \"bill_length_mm\": 0,",
        "... ",
        "  \"species_Chinstrap\": False,",
        "... ",
        "  \"species_Gentoo\": False,",
        "... ",
        "  \"sex_male\": False",
        "... ",
        "}",
        ">>> ",
        "req = requests.post('http://127.0.0.1:8080/predict', json = [req_data])",
        ">>> ",
        "res = req.json().get('predict')[0]",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'req' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "import requests",
        ">>> ",
        "from request import post",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 119;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 119, in _find_and_load_hook\n    return _run_hook(name, _hook)\n  File \"\u001B[90m\u001B]8;line = 93;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 93, in _run_hook\n    module = hook()\n  File \"\u001B[90m\u001B]8;line = 117;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 117, in _hook\n    return _find_and_load(name, import_)\nModuleNotFoundError: No module named 'request'\n",
        ">>> ",
        "from req import json",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 119;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 119, in _find_and_load_hook\n    return _run_hook(name, _hook)\n  File \"\u001B[90m\u001B]8;line = 93;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 93, in _run_hook\n    module = hook()\n  File \"\u001B[90m\u001B]8;line = 117;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 117, in _hook\n    return _find_and_load(name, import_)\nModuleNotFoundError: No module named 'req'\n",
        ">>> ",
        "req_data = {",
        "... ",
        "  \"bill_length_mm\": 0,",
        "... ",
        "  \"species_Chinstrap\": False,",
        "... ",
        "  \"species_Gentoo\": False,",
        "... ",
        "  \"sex_male\": False",
        "... ",
        "}",
        ">>> ",
        "req = requests.post('http://127.0.0.1:8080/predict', json = [req_data])",
        "Traceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 198;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 198, in _new_conn\n    sock = connection.create_connection(\n  File \"\u001B[90m\u001B]8;line = 85;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 85, in create_connection\n    raise err\n  File \"\u001B[90m\u001B]8;line = 73;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 793;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 793, in urlopen\n    response = self._make_request(\n  File \"\u001B[90m\u001B]8;line = 496;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 496, in _make_request\n    conn.request(\n  File \"\u001B[90m\u001B]8;line = 400;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 400, in request\n    self.endheaders()\n  File \"\u001B[90m\u001B]8;line = 1248;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1248, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"\u001B[90m\u001B]8;line = 1008;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1008, in _send_output\n    self.send(msg)\n  File \"\u001B[90m\u001B]8;line = 948;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 948, in send\n    self.connect()\n  File \"\u001B[90m\u001B]8;line = 238;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 238, in connect\n    self.sock = self._new_conn()\n  File \"\u001B[90m\u001B]8;line = 213;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 213, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E7EE477550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 486;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 486, in send\n    resp = conn.urlopen(\n  File \"\u001B[90m\u001B]8;line = 847;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 847, in urlopen\n    retries = retries.increment(\n  File \"\u001B[90m\u001B]8;line = 515;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\retry.py\u001B]8;;\u0007\u001B[39m\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE477550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 115;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 59;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 589;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"\u001B[90m\u001B]8;line = 703;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 519;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE477550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n",
        ">>> ",
        "res = req.json().get('predict')[0]",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'req' is not defined\n",
        ">>> ",
        "",
        ">>> ",
        "import requests",
        ">>> ",
        "from request import post",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 119;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 119, in _find_and_load_hook\n    return _run_hook(name, _hook)\n  File \"\u001B[90m\u001B]8;line = 93;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 93, in _run_hook\n    module = hook()\n  File \"\u001B[90m\u001B]8;line = 117;file://C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u0007C:\\Users\\C25Joshua.Pym\\AppData\\Local\\R\\win-library\\4.2\\reticulate\\python\\rpytools\\loader.py\u001B]8;;\u0007\u001B[39m\", line 117, in _hook\n    return _find_and_load(name, import_)\nModuleNotFoundError: No module named 'request'\n",
        ">>> ",
        "from req import json",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nImportError: cannot import name 'json' from 'req' (C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\req.py)\n",
        ">>> ",
        "req_data = {",
        "... ",
        "  \"bill_length_mm\": 0,",
        "... ",
        "  \"species_Chinstrap\": False,",
        "... ",
        "  \"species_Gentoo\": False,",
        "... ",
        "  \"sex_male\": False",
        "... ",
        "}",
        ">>> ",
        "req = requests.post('http://127.0.0.1:8080/predict', json = [req_data])",
        "Traceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 198;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 198, in _new_conn\n    sock = connection.create_connection(\n  File \"\u001B[90m\u001B]8;line = 85;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 85, in create_connection\n    raise err\n  File \"\u001B[90m\u001B]8;line = 73;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\connection.py\u001B]8;;\u0007\u001B[39m\", line 73, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 793;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 793, in urlopen\n    response = self._make_request(\n  File \"\u001B[90m\u001B]8;line = 496;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 496, in _make_request\n    conn.request(\n  File \"\u001B[90m\u001B]8;line = 400;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 400, in request\n    self.endheaders()\n  File \"\u001B[90m\u001B]8;line = 1248;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1248, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"\u001B[90m\u001B]8;line = 1008;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 1008, in _send_output\n    self.send(msg)\n  File \"\u001B[90m\u001B]8;line = 948;file://C:\\Program Files\\Python39\\Lib\\http\\client.py\u0007C:\\Program Files\\Python39\\lib\\http\\client.py\u001B]8;;\u0007\u001B[39m\", line 948, in send\n    self.connect()\n  File \"\u001B[90m\u001B]8;line = 238;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 238, in connect\n    self.sock = self._new_conn()\n  File \"\u001B[90m\u001B]8;line = 213;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connection.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connection.py\u001B]8;;\u0007\u001B[39m\", line 213, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E7EE547D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\u001B[90m\u001B]8;line = 486;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 486, in send\n    resp = conn.urlopen(\n  File \"\u001B[90m\u001B]8;line = 847;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\connectionpool.py\u001B]8;;\u0007\u001B[39m\", line 847, in urlopen\n    retries = retries.increment(\n  File \"\u001B[90m\u001B]8;line = 515;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\urllib3\\util\\retry.py\u001B]8;;\u0007\u001B[39m\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE547D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"\u001B[90m\u001B]8;line = 115;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 59;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\api.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\api.py\u001B]8;;\u0007\u001B[39m\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 589;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"\u001B[90m\u001B]8;line = 703;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\sessions.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\sessions.py\u001B]8;;\u0007\u001B[39m\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"\u001B[90m\u001B]8;line = 519;file://C:\\Users\\C25Joshua.Pym\\OneDrive - afacademy.af.edu\\Documents\\Final Project for Joshua Pym\\.venv\\Lib\\site-packages\\requests\\adapters.py\u0007C:\\Users\\C25JOS~1.PYM\\ONEDRI~1.EDU\\DOCUME~1\\FINALP~1\\VENV~1\\lib\\site-packages\\requests\\adapters.py\u001B]8;;\u0007\u001B[39m\", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7EE547D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n",
        ">>> ",
        "res = req.json().get('predict')[0]",
        "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'req' is not defined\n",
        ">>> ",
        "",
        "\nRestarting R session...\n\n"
    ]
}